config/routes.rb
LanguageLesson::Application.routes.draw do
  resources :activities
  
  resources :page_elements

  resources :content_blocks

  resources :pages

  resources :answers

  resources :questions
  resources :prompted_audio_questions

  resources :question_attempts do
    resources :question_attempt_responses
  end

  resources :question_attempt_responses

  resources :lessons do
    resources :questions

    member do
      get :by_activity
    end
    
    collection do
      get :by_language
    end
  end

  resources :courses

  resources :recordings do
    member do
      post :receive
    end
  end

  resources :lesson_attempts do
    resources :question_attempts do
      collection do
        post :add
      end
    end
  end

  resources :languages do
    collection do
      get :with_lessons
    end
  end
  
  namespace :lti do
    resources :courses
    resources :lessons
    resources :questions
    resources :prompted_audio_questions
    resources :lesson_attempts do
      resources :question_attempts
    end
    
    post 'start' => 'lti#start', :as => 'start_lti'
    post 'params' => 'lti#show_params', :as => 'show_params'
    get 'choose_lesson' => 'lti#choose_lesson', :as => 'choose_lesson'
    get 'start_lesson/(:lesson_id)' => 'lessons#start_lesson', :as => 'start_lesson'
    post 'lesson_attempts/start_attempt/(:lesson_id)' => 'lesson_attempts#start_attempt', :as => 'start_lesson_attempt'
    get 'lesson_attempts/show_page_element/(:lesson_attempt_id)/(:page_element_id)' => 'lesson_attempts#show_page_element', :as => 'show_lesson_attempt_page_element'
  end

  get '/home/backbone' => 'home#backbone'
  get '/home/test' => 'home#test'

  get '/backbone' => 'backbone#index'

  get '/backbone/signS3put' => 'backbone#signS3put'

  get 'lesson_attempts/:lesson_attempt_id/questions/:question_id/users/:user_id' => 'question_attempts#find_by_lesson_attempt_question_and_user', :as => 'find_question_attempt_by_lesson_attempt_question_and_user'

  get 'lesson_attempts/by_lesson_and_user/:lesson_id/:user_id' => 'lesson_attempts#by_lesson_and_user', :as => 'by_lesson_and_user_lesson_attempts'
  
  get 'lesson_attempts/by_activity/:activity_id' => 'lesson_attempts#by_activity', :as => 'by_activity_lesson_attempts'


  root :to => 'backbone#index'
end

app/models/content_block.rb
class ContentBlock < ActiveRecord::Base
  has_one :lesson_element, as: :presentable
  has_one :recording, -> { where(recording_type: Recording::RECORDING_TYPE_STANDARD) }, as: :recordable, dependent: :destroy

  def type
    "ContentBlock"
  end
end

app/controllers/content_blocks_controller.rb
class ContentBlocksController < ApplicationController
  # GET /content_blocks
  # GET /content_blocks.json
  def index
    @content_blocks = ContentBlock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @content_blocks }
    end
  end

  # GET /content_blocks/1
  # GET /content_blocks/1.json
  def show
    @content_block = ContentBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @content_block }
    end
  end

  # GET /content_blocks/new
  # GET /content_blocks/new.json
  def new
    @content_block = ContentBlock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @content_block }
    end
  end

  # GET /content_blocks/1/edit
  def edit
    @content_block = ContentBlock.find(params[:id])
  end

  # POST /content_blocks
  # POST /content_blocks.json
  def create
    @content_block = ContentBlock.new(params[:content_block])

    respond_to do |format|
      if @content_block.save
        format.html { redirect_to @content_block, notice: 'Content block was successfully created.' }
        format.json { render json: @content_block, status: :created, location: @content_block }
      else
        format.html { render action: "new" }
        format.json { render json: @content_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /content_blocks/1
  # PUT /content_blocks/1.json
  def update
    @content_block = ContentBlock.find(params[:id])

    respond_to do |format|
      if @content_block.update_attributes(params[:content_block])
        format.html { redirect_to @content_block, notice: 'Content block was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @content_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /content_blocks/1
  # DELETE /content_blocks/1.json
  def destroy
    @content_block = ContentBlock.find(params[:id])
    @content_block.destroy

    respond_to do |format|
      format.html { redirect_to content_blocks_url }
      format.json { head :no_content }
    end
  end
end

app/views/content_blocks/_form.html.haml
= form_for @content_block do |f|
  - if @content_block.errors.any?
    #error_explanation
      %h2= "#{pluralize(@content_block.errors.count, "error")} prohibited this content_block from being saved:"
      %ul
        - @content_block.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :page
    = f.text_field :page
  .actions
    = f.submit 'Save'

app/views/content_blocks/edit.html.haml
%h1 Editing content_block

= render 'form'

= link_to 'Show', @content_block
\|
= link_to 'Back', content_blocks_path

app/views/content_blocks/index.html.haml
%h1 Listing content_blocks

%table
  %tr
    %th Page
    %th
    %th
    %th

  - @content_blocks.each do |content_block|
    %tr
      %td= content_block.page
      %td= link_to 'Show', content_block
      %td= link_to 'Edit', edit_content_block_path(content_block)
      %td= link_to 'Destroy', content_block, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Content block', new_content_block_path

app/views/content_blocks/new.html.haml
%h1 New content_block

= render 'form'

= link_to 'Back', content_blocks_path

app/views/content_blocks/show.html.haml
%p#notice= notice

%p
  %b Page:
  = @content_block.page_element.page.title

%p
  %b Content:
  = @content_block.content.html_safe

- unless @content_block.recordings.empty?
  %h3 Recordings
  %ul
    - @question.recordings.each do |recording|
      %li
        %audio{:id => 'audio-player', 'controls' => '', 'data-fileurl' => recording.file.url, :src => recording.file.url}
  
= link_to 'Edit', edit_content_block_path(@content_block)
\|
= link_to 'Back', content_blocks_path