config/routes.rb
LanguageLesson::Application.routes.draw do
  resources :activities
  
  resources :page_elements

  resources :content_blocks

  resources :pages

  resources :answers

  resources :questions
  resources :prompted_audio_questions

  resources :question_attempts do
    resources :question_attempt_responses
  end

  resources :question_attempt_responses

  resources :lessons do
    resources :questions

    member do
      get :by_activity
    end
    
    collection do
      get :by_language
    end
  end

  resources :courses

  resources :recordings do
    member do
      post :receive
    end
  end

  resources :lesson_attempts do
    resources :question_attempts do
      collection do
        post :add
      end
    end
  end

  resources :languages do
    collection do
      get :with_lessons
    end
  end
  
  namespace :lti do
    resources :courses
    resources :lessons
    resources :questions
    resources :prompted_audio_questions
    resources :lesson_attempts do
      resources :question_attempts
    end
    
    post 'start' => 'lti#start', :as => 'start_lti'
    post 'params' => 'lti#show_params', :as => 'show_params'
    get 'choose_lesson' => 'lti#choose_lesson', :as => 'choose_lesson'
    get 'start_lesson/(:lesson_id)' => 'lessons#start_lesson', :as => 'start_lesson'
    post 'lesson_attempts/start_attempt/(:lesson_id)' => 'lesson_attempts#start_attempt', :as => 'start_lesson_attempt'
    get 'lesson_attempts/show_page_element/(:lesson_attempt_id)/(:page_element_id)' => 'lesson_attempts#show_page_element', :as => 'show_lesson_attempt_page_element'
  end

  get '/home/backbone' => 'home#backbone'
  get '/home/test' => 'home#test'

  get '/backbone' => 'backbone#index'

  get '/backbone/signS3put' => 'backbone#signS3put'

  get 'lesson_attempts/:lesson_attempt_id/questions/:question_id/users/:user_id' => 'question_attempts#find_by_lesson_attempt_question_and_user', :as => 'find_question_attempt_by_lesson_attempt_question_and_user'

  get 'lesson_attempts/by_lesson_and_user/:lesson_id/:user_id' => 'lesson_attempts#by_lesson_and_user', :as => 'by_lesson_and_user_lesson_attempts'
  
  get 'lesson_attempts/by_activity/:activity_id' => 'lesson_attempts#by_activity', :as => 'by_activity_lesson_attempts'


  root :to => 'backbone#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  #attr_accessible :title, :content
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
    @answer = Answer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @answer = Answer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # GET /answers/1/edit
  def edit
    @answer = Answer.find(params[:id])
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(params[:answer])

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render json: @answer, status: :created, location: @answer }
      else
        format.html { render action: "new" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /answers/1
  # PUT /answers/1.json
  def update
    @answer = Answer.find(params[:id])

    respond_to do |format|
      if @answer.update_attributes(params[:answer])
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer = Answer.find(params[:id])
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end
end

app/views/answers/_form.html.haml
= form_for @answer do |f|
  - if @answer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@answer.errors.count, "error")} prohibited this answer from being saved:"
      %ul
        - @answer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :question
    = f.text_field :question
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :text
    = f.text_field :text
  .actions
    = f.submit 'Save'

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %tr
    %th Question
    %th Name
    %th Text
    %th
    %th
    %th

  - @answers.each do |answer|
    %tr
      %td= answer.question
      %td= answer.name
      %td= answer.text
      %td= link_to 'Show', answer
      %td= link_to 'Edit', edit_answer_path(answer)
      %td= link_to 'Destroy', answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b Question:
  = @answer.question
%p
  %b Name:
  = @answer.name
%p
  %b Text:
  = @answer.text

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path