config/routes.rb
LanguageLesson::Application.routes.draw do
  resources :activities
  
  resources :page_elements

  resources :content_blocks

  resources :pages

  resources :answers

  resources :questions
  resources :prompted_audio_questions

  resources :question_attempts do
    resources :question_attempt_responses
  end

  resources :question_attempt_responses

  resources :lessons do
    resources :questions

    member do
      get :by_activity
    end
    
    collection do
      get :by_language
    end
  end

  resources :courses

  resources :recordings do
    member do
      post :receive
    end
  end

  resources :lesson_attempts do
    resources :question_attempts do
      collection do
        post :add
      end
    end
  end

  resources :languages do
    collection do
      get :with_lessons
    end
  end
  
  namespace :lti do
    resources :courses
    resources :lessons
    resources :questions
    resources :prompted_audio_questions
    resources :lesson_attempts do
      resources :question_attempts
    end
    
    post 'start' => 'lti#start', :as => 'start_lti'
    post 'params' => 'lti#show_params', :as => 'show_params'
    get 'choose_lesson' => 'lti#choose_lesson', :as => 'choose_lesson'
    get 'start_lesson/(:lesson_id)' => 'lessons#start_lesson', :as => 'start_lesson'
    post 'lesson_attempts/start_attempt/(:lesson_id)' => 'lesson_attempts#start_attempt', :as => 'start_lesson_attempt'
    get 'lesson_attempts/show_page_element/(:lesson_attempt_id)/(:page_element_id)' => 'lesson_attempts#show_page_element', :as => 'show_lesson_attempt_page_element'
  end

  get '/home/backbone' => 'home#backbone'
  get '/home/test' => 'home#test'

  get '/backbone' => 'backbone#index'

  get '/backbone/signS3put' => 'backbone#signS3put'

  get 'lesson_attempts/:lesson_attempt_id/questions/:question_id/users/:user_id' => 'question_attempts#find_by_lesson_attempt_question_and_user', :as => 'find_question_attempt_by_lesson_attempt_question_and_user'

  get 'lesson_attempts/by_lesson_and_user/:lesson_id/:user_id' => 'lesson_attempts#by_lesson_and_user', :as => 'by_lesson_and_user_lesson_attempts'
  
  get 'lesson_attempts/by_activity/:activity_id' => 'lesson_attempts#by_activity', :as => 'by_activity_lesson_attempts'


  root :to => 'backbone#index'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  has_many :course_lessons
  has_many :courses, through: :course_lessons
  #attr_accessible :name, :graded, :auto_grading, :hide_previous_answer, :submission_limited, :submission_limit, :course, :default_correct, :default_incorrect, :max_score
  has_many :questions
  has_many :lesson_elements
  belongs_to :language
  
  def full_name
    "#{course.name} - #{self.name}"
  end

  def presentables
    lesson_elements.rank(:row_order).collect {|e| e.presentable}
  end

  scope :by_activity, -> (activity_id) { where("id in (SELECT doable_id FROM activities WHERE doable_type = 'Lesson' and id = ?)", activity_id).first }

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  respond_to :html, :json

  def index
    @lessons = Lesson.all
  end
 
  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new

    respond_to do |format|
      format.json { render json: @lesson }
    end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def create
    @lesson = Lesson.new(params[:lesson])

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render json: @lesson, status: :created, location: @lesson }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @lesson = Lesson.find(params[:id])

    respond_to do |format|
      if @lesson.update_attributes(params[:lesson])
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy

    respond_to do |format|
      format.html { redirect_to lessons_url }
      format.json { head :no_content }
    end
  end

  def by_language
    @languages = Language.includes(:lessons).all
  end
end

app/controllers/lti/lessons_controller.rb
class Lti::LessonsController < Lti::LtiController
  def start_lesson
    user = User.find(session[:user_id])
    @lesson = Lesson.find(params[:lesson_id])
  end
end

app/views/lessons/_form.html.haml
= form_for @lesson, :html => {:class => 'form-horizontal'} do |f|
  - if @lesson.errors.any?
    #error_explanation
      %h2= "#{pluralize(@lesson.errors.count, "error")} prohibited this lesson from being saved:"
      %ul
        - @lesson.errors.full_messages.each do |msg|
          %li= msg

  -#.control-group
  -#  = f.label :course, :class => 'control-label'
  -#  .controls= f.text_field :course
  .control-group
    = f.label :name, :class => 'control-label'
    .controls= f.text_field :name
  .control-group
    = f.label :graded, :class => 'control-label'
    .controls= f.check_box :graded
  .control-group
    = f.label :auto_grading, :class => 'control-label'
    .controls= f.check_box :auto_grading
  .control-group
    = f.label :hide_previous_answer, :class => 'control-label'
    .controls= f.check_box :hide_previous_answer
  .control-group
    = f.label :submission_limited, :class => 'control-label'
    .controls= f.check_box :submission_limited
  .control-group
    = f.label :submission_limit, :class => 'control-label'
    .controls= f.text_field :submission_limit
  .actions
    = f.submit 'Save'

app/views/lessons/by_language.html.haml
- @languages.each do |language|
  - unless language.lessons.empty?
    %h4= language.name
    %ul
      - language.lessons.each do |lesson|
        %li= link_to lesson.name, "/backbone#lessons/#{lesson.id}/attempt", target: '_blank'

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show', @lesson
\|
= link_to 'Back', lessons_path

app/views/lessons/index.html.haml
%h1 Listing lessons

%table.table.table-striped
  %tr
    %th Name
    %th Courses
    %th
    %th
    %th

  - @lessons.each do |lesson|
    %tr
      %td= lesson.name
      %td
        - lesson.courses.each do |course|
          = link_to course.name, course
          %br 
      %td= link_to 'Show', lesson
      %td= link_to 'Edit', edit_lesson_path(lesson)
      %td= link_to 'Destroy', lesson, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form'

= link_to 'Back', lessons_path

app/views/lessons/show.html.haml
%p#notice= notice

%p
  %b Courses
  %ul
    - @lesson.courses.each do |course|
      %li= link_to course.name, course
%p
  %b Name:
  = @lesson.name

%h3 Pages
#pages_box
  %ul
    - @lesson.pages.rank(:row_order).each do |page|
      %li= link_to page.title, page

= link_to 'New Question', new_lesson_question_path(@lesson)

= link_to 'Edit', edit_lesson_path(@lesson)
\|
= link_to 'Back', lessons_path